// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpJieW8NiGCu-0G4hV_FUXaO4_uQft7cY',
    appId: '1:233422797747:web:73295e54a730a61f2669c6',
    messagingSenderId: '233422797747',
    projectId: 'instaclone-061',
    authDomain: 'instaclone-061.firebaseapp.com',
    storageBucket: 'instaclone-061.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFYw3Fah4WmvCbj3h0flppSyAO3prN8I',
    appId: '1:233422797747:android:fbd990c57f6dc9fd2669c6',
    messagingSenderId: '233422797747',
    projectId: 'instaclone-061',
    storageBucket: 'instaclone-061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfJbRA5Fmy6eVIyB1GD4mDFmEW64h0mDk',
    appId: '1:233422797747:ios:6b5fc4483a7bbd112669c6',
    messagingSenderId: '233422797747',
    projectId: 'instaclone-061',
    storageBucket: 'instaclone-061.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfJbRA5Fmy6eVIyB1GD4mDFmEW64h0mDk',
    appId: '1:233422797747:ios:6b5fc4483a7bbd112669c6',
    messagingSenderId: '233422797747',
    projectId: 'instaclone-061',
    storageBucket: 'instaclone-061.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpJieW8NiGCu-0G4hV_FUXaO4_uQft7cY',
    appId: '1:233422797747:web:6f1608aa71e53b5a2669c6',
    messagingSenderId: '233422797747',
    projectId: 'instaclone-061',
    authDomain: 'instaclone-061.firebaseapp.com',
    storageBucket: 'instaclone-061.firebasestorage.app',
  );
}
